name: Add contributors
on:
    schedule:
        - cron: '0 10 * * *'

jobs:
    add-contributors:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: BobAnkh/add-contributors@master
              with:
                  CONTRIBUTOR: '### Contributors'
                  COLUMN_PER_ROW: '10'
                  ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  IMG_WIDTH: '50'
                  FONT_SIZE: '14'
                  PATH: '/README.md'
                  COMMIT_MESSAGE: 'docs(README): update contributors'
                  AVATAR_SHAPE: 'round'
                  IGNORED_CONTRIBUTORS: 'apps/github-actions, apps/dependabot'
                  BRANCH: 'main'
